// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWeiP7aEmFBCj7uEQbsZaJttVKV99_Qos',
    appId: '1:782441562287:web:a98b38490844b5ad4fd45a',
    messagingSenderId: '782441562287',
    projectId: 'facebookclone-79d24',
    authDomain: 'facebookclone-79d24.firebaseapp.com',
    storageBucket: 'facebookclone-79d24.appspot.com',
    measurementId: 'G-S865PJQ5N0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7VvQADnNQekCxj2cxW_iV-Lm-g5aUwtg',
    appId: '1:782441562287:android:5414ea87fbfcd98c4fd45a',
    messagingSenderId: '782441562287',
    projectId: 'facebookclone-79d24',
    storageBucket: 'facebookclone-79d24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3kbo4sH-yiO2WxEz8VpvQOZxFsRLVV8Y',
    appId: '1:782441562287:ios:4e1632c18ebb15c34fd45a',
    messagingSenderId: '782441562287',
    projectId: 'facebookclone-79d24',
    storageBucket: 'facebookclone-79d24.appspot.com',
    iosClientId: '782441562287-fsug071n9aidqphaoahpi6b7bdd8ajgm.apps.googleusercontent.com',
    iosBundleId: 'com.example.facebookclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3kbo4sH-yiO2WxEz8VpvQOZxFsRLVV8Y',
    appId: '1:782441562287:ios:d0dbab6e6689a86a4fd45a',
    messagingSenderId: '782441562287',
    projectId: 'facebookclone-79d24',
    storageBucket: 'facebookclone-79d24.appspot.com',
    iosClientId: '782441562287-f9kj4erieh2u65rgmo7fi89djeogk025.apps.googleusercontent.com',
    iosBundleId: 'com.example.facebookclone.RunnerTests',
  );
}
